name: Format

on:
  pull_request:
  push:
    branches:
      - master
      - staging
      - trying

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install toolchain from rust-toolchain.toml
        run: rustup show
      - name: Format
        run: cargo fmt --all -- --check
      - name: Integration Test Format
        working-directory: ./tests/test-kernels
        run: cargo fmt --all -- --check
